"""Edge-TTS fallback backend — cloud-based Microsoft neural voices.

Kept as a fallback for environments without local Kokoro support or
when higher voice variety is needed. Requires network access.

WARNING: edge-tts reverse-engineers an undocumented Microsoft API.
It can break without notice. Prefer KokoroBackend for production.
"""

from __future__ import annotations

import io
import logging
from typing import TYPE_CHECKING

import edge_tts

from .tts_backend import TTSBackend, TTSVoiceConfig

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator

logger = logging.getLogger(__name__)

# Map Kokoro voice_ids back to Edge Neural voice identifiers.
# This lets the rest of the codebase use agent→voice mapping from tts_backend.py
# while this backend translates to Edge-specific IDs.
_KOKORO_TO_EDGE: dict[str, str] = {
    "am_michael": "en-US-GuyNeural",
    "af_sarah": "en-US-AriaNeural",
    "af_bella": "en-US-JennyNeural",
    "af_nicole": "en-US-MichelleNeural",
    "bf_emma": "en-GB-SoniaNeural",
    "af_jessica": "en-US-AriaNeural",
    "am_adam": "en-US-AndrewNeural",
    "af_sky": "en-US-AmberNeural",
    "af_kore": "en-US-JaneNeural",
    "af_nova": "en-US-NancyNeural",
    "af_heart": "en-US-AriaNeural",
}


class EdgeTTSBackend(TTSBackend):
    """Fallback TTS backend using Microsoft Edge neural voices via edge-tts."""

    async def synthesize(self, text: str, voice: TTSVoiceConfig) -> bytes:
        """Generate MP3 audio bytes from text using edge-tts."""
        if not text.strip():
            return b""

        # Resolve voice ID: use Edge-specific ID if available
        edge_voice = _KOKORO_TO_EDGE.get(voice.voice_id, voice.voice_id)

        # Convert speed multiplier to edge-tts rate string (e.g. 0.95 → "-5%")
        rate_pct = (voice.speed - 1.0) * 100
        rate_str = f"{rate_pct:+.0f}%"

        # Convert pitch multiplier to edge-tts pitch string
        pitch_pct = (voice.pitch - 1.0) * 100
        pitch_str = f"{pitch_pct:+.0f}%"

        logger.info(
            "Edge-TTS: voice=%s, rate=%s, pitch=%s, text_len=%d",
            edge_voice,
            rate_str,
            pitch_str,
            len(text),
        )

        communicate = edge_tts.Communicate(
            text,
            voice=edge_voice,
            rate=rate_str,
            pitch=pitch_str,
        )

        buf = io.BytesIO()
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                buf.write(chunk["data"])

        audio_bytes = buf.getvalue()
        logger.debug("Edge-TTS generated %d bytes of MP3", len(audio_bytes))
        return audio_bytes

    async def stream_synthesize(
        self, text: str, voice: TTSVoiceConfig
    ) -> AsyncGenerator[bytes, None]:
        """Yield MP3 audio chunks as they are generated by edge-tts."""
        if not text.strip():
            return

        # Resolve voice ID: use Edge-specific ID if available
        edge_voice = _KOKORO_TO_EDGE.get(voice.voice_id, voice.voice_id)

        # Convert speed multiplier to edge-tts rate string (e.g. 0.95 → "-5%")
        rate_pct = (voice.speed - 1.0) * 100
        rate_str = f"{rate_pct:+.0f}%"

        # Convert pitch multiplier to edge-tts pitch string
        pitch_pct = (voice.pitch - 1.0) * 100
        pitch_str = f"{pitch_pct:+.0f}%"

        communicate = edge_tts.Communicate(
            text,
            voice=edge_voice,
            rate=rate_str,
            pitch=pitch_str,
        )

        async for chunk in communicate.stream():
            if chunk["type"] == "audio" and chunk["data"]:
                yield chunk["data"]

    def available_voices(self) -> list[TTSVoiceConfig]:
        """List the Edge Neural voices we use for agent mapping."""
        return [
            TTSVoiceConfig("Guy", "en-US-GuyNeural"),
            TTSVoiceConfig("Aria", "en-US-AriaNeural"),
            TTSVoiceConfig("Jenny", "en-US-JennyNeural"),
            TTSVoiceConfig("Michelle", "en-US-MichelleNeural"),
            TTSVoiceConfig("Sonia", "en-GB-SoniaNeural"),
            TTSVoiceConfig("Andrew", "en-US-AndrewNeural"),
            TTSVoiceConfig("Amber", "en-US-AmberNeural"),
            TTSVoiceConfig("Jane", "en-US-JaneNeural"),
            TTSVoiceConfig("Nancy", "en-US-NancyNeural"),
        ]

    @property
    def sample_rate(self) -> int:
        # Edge-TTS outputs MP3 at 24kHz
        return 24000
