"""Kokoro-82M TTS backend — local, Apache 2.0 licensed neural speech synthesis.

Uses the `kokoro` package (pip install kokoro soundfile) which wraps the
82M-parameter StyleTTS 2 model. Runs on CPU with ~350 MB memory footprint.

Requires system dependency: espeak-ng (for grapheme-to-phoneme conversion).
"""

from __future__ import annotations

import io
import logging
import wave
from typing import TYPE_CHECKING, Any

import numpy as np

from .tts_backend import TTSBackend, TTSVoiceConfig

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator

logger = logging.getLogger(__name__)

# Kokoro's native sample rate
_SAMPLE_RATE = 24000


class KokoroBackend(TTSBackend):
    """Kokoro-82M TTS backend for local, CPU-friendly speech synthesis.

    Lazy-loads the model on first synthesize() call to avoid startup latency
    when TTS is disabled.
    """

    def __init__(self) -> None:
        self._pipelines: dict[str, Any] = {}  # lang_code → KPipeline

    def _get_pipeline(self, lang_code: str = "a") -> Any:
        """Get or create a KPipeline for the given language code.

        Caches pipelines per language so we don't reload the model.
        """
        if lang_code not in self._pipelines:
            try:
                from kokoro import KPipeline
            except ImportError as e:
                raise ImportError(
                    "Kokoro TTS not installed. Run: pip install kokoro soundfile\n"
                    "Also ensure espeak-ng is installed on your system."
                ) from e

            logger.info("Loading Kokoro-82M pipeline (lang_code=%s)...", lang_code)
            self._pipelines[lang_code] = KPipeline(lang_code=lang_code)
            logger.info("Kokoro-82M pipeline ready (lang_code=%s)", lang_code)

        return self._pipelines[lang_code]

    def _to_wav(self, audio: Any) -> bytes:
        """Convert float32 [-1, 1] audio (numpy ndarray or torch tensor) to 16-bit PCM WAV bytes."""
        # Newer kokoro releases yield torch.Tensor; coerce to numpy.
        if hasattr(audio, "detach"):
            audio = audio.detach().cpu().numpy()
        pcm_data = (audio * 32767).astype(np.int16)
        wav_buffer = io.BytesIO()
        with wave.open(wav_buffer, "wb") as wav:
            wav.setnchannels(1)  # Kokoro outputs mono
            wav.setsampwidth(2)  # 16-bit
            wav.setframerate(_SAMPLE_RATE)
            wav.writeframes(pcm_data.tobytes())
        return wav_buffer.getvalue()

    async def synthesize(self, text: str, voice: TTSVoiceConfig) -> bytes:
        """Generate WAV audio bytes from text using Kokoro-82M.

        The pipeline is synchronous internally but we wrap it for the async
        interface. For true non-blocking in production, use run_in_executor().

        Raises:
            ValueError: If voice config is invalid
            RuntimeError: If synthesis fails
        """
        if not text.strip():
            return b""

        # Validate voice config
        if not voice.voice_id:
            raise ValueError("voice_id cannot be empty")

        try:
            pipeline = self._get_pipeline(voice.lang_code)
        except ValueError as e:
            logger.error("Invalid lang_code '%s': %s", voice.lang_code, e)
            raise

        try:
            # Kokoro's pipeline yields (graphemes, phonemes, audio_ndarray) segments.
            # NOTE: voice.pitch is not passed — KPipeline has no pitch parameter.
            # pitch is kept in TTSVoiceConfig for API uniformity with edge-tts fallback.
            audio_segments: list[np.ndarray] = []
            for _gs, _ps, audio in pipeline(text, voice=voice.voice_id, speed=voice.speed):
                audio_segments.append(audio)
        except Exception as e:
            logger.error(
                "Kokoro synthesis failed for voice=%s: %s", voice.voice_id, e, exc_info=True
            )
            raise RuntimeError(f"Kokoro TTS synthesis failed: {e}") from e

        if not audio_segments:
            logger.warning("Kokoro produced no audio for text: %s", text[:60])
            return b""

        # Concatenate all segments into one continuous audio array
        full_audio = np.concatenate(audio_segments)
        return self._to_wav(full_audio)

    async def stream_synthesize(
        self, text: str, voice: TTSVoiceConfig
    ) -> AsyncGenerator[bytes, None]:
        """Yield WAV audio chunks as they are generated by Kokoro-82M.

        This provides the lowest possible latency by yielding each sentence
        segment immediately after it is synthesized.
        """
        if not text.strip():
            return

        if not voice.voice_id:
            raise ValueError("voice_id cannot be empty")

        try:
            pipeline = self._get_pipeline(voice.lang_code)
        except ValueError as e:
            logger.error("Invalid lang_code '%s': %s", voice.lang_code, e)
            raise

        try:
            # Iterate through segments and yield each one as a valid WAV
            for _gs, _ps, audio in pipeline(text, voice=voice.voice_id, speed=voice.speed):
                if audio is not None and len(audio) > 0:
                    yield self._to_wav(audio)
        except Exception as e:
            logger.error("Kokoro streaming synthesis failed: %s", e, exc_info=True)
            raise RuntimeError(f"Kokoro streaming TTS failed: {e}") from e

    def available_voices(self) -> list[TTSVoiceConfig]:
        """List Kokoro's built-in American/British English voices."""
        return [
            # American Female
            TTSVoiceConfig("Heart", "af_heart"),
            TTSVoiceConfig("Alloy", "af_alloy"),
            TTSVoiceConfig("Bella", "af_bella"),
            TTSVoiceConfig("Jessica", "af_jessica"),
            TTSVoiceConfig("Kore", "af_kore"),
            TTSVoiceConfig("Nicole", "af_nicole"),
            TTSVoiceConfig("Nova", "af_nova"),
            TTSVoiceConfig("River", "af_river"),
            TTSVoiceConfig("Sarah", "af_sarah"),
            TTSVoiceConfig("Sky", "af_sky"),
            # American Male
            TTSVoiceConfig("Adam", "am_adam"),
            TTSVoiceConfig("Echo", "am_echo"),
            TTSVoiceConfig("Eric", "am_eric"),
            TTSVoiceConfig("Liam", "am_liam"),
            TTSVoiceConfig("Michael", "am_michael"),
            TTSVoiceConfig("Onyx", "am_onyx"),
            # British Female
            TTSVoiceConfig("Alice", "bf_alice", lang_code="b"),
            TTSVoiceConfig("Emma", "bf_emma", lang_code="b"),
            TTSVoiceConfig("Isabella", "bf_isabella", lang_code="b"),
            TTSVoiceConfig("Lily", "bf_lily", lang_code="b"),
            # British Male
            TTSVoiceConfig("Daniel", "bm_daniel", lang_code="b"),
            TTSVoiceConfig("George", "bm_george", lang_code="b"),
            TTSVoiceConfig("Lewis", "bm_lewis", lang_code="b"),
        ]

    @property
    def sample_rate(self) -> int:
        return _SAMPLE_RATE
