repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix, --unsafe-fixes, --exit-non-zero-on-fix, --config=pyproject.toml]

  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: uv run --no-active ty check
        args: [agents, hosts/cli, hosts/gui, mcp_servers, shared/src, tests]
        language: system
        types: [python]
        pass_filenames: false
